#!/bin/bash

# this file is for hub.docker.com
# in order to do 'automatic build'
# of corresponding image located there

#docker build \
#--build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
#--build-arg VCS_REF=`git rev-parse --short HEAD` \
#--build-arg VERSION=$DOCKER_TAG \
#-t $IMAGE_NAME .

#experiment
docker-compose \
-f docker-compose2_hub.docker.com.yml \
build \
--build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
--build-arg VCS_REF=`git rev-parse --short HEAD` \
--build-arg VERSION=$DOCKER_TAG