#!/bin/bash

# this file is for hub.docker.com
# in order to do 'automatic build'
# of corresponding image located there

docker build \
--build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
--build-arg VCS_REF=`git rev-parse --short HEAD` \
--build-arg VERSION=$DOCKER_TAG \
-t $IMAGE_NAME .

# do not use below; not clear how to make it working;
# the above, simple build approach, would work fine;
# to use below, first have to have supporting version 
# on top of docker-compose.yml (last 
# time, it was 3.3), but there are more setting up 
#docker-compose build \
#--build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
#--build-arg VCS_REF=`git rev-parse --short HEAD` \
#--build-arg VERSION=$DOCKER_TAG